package state

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

// Runner status constants. Stored as text so additions don't need migrations.
const (
	RunnerPendingAdmit       = "pending_admit"
	RunnerIdle               = "idle"
	RunnerAvailable          = "available"
	RunnerBusy               = "busy"
	RunnerDeliveredPendingAck = "delivered_pending_ack"
	RunnerOffline            = "offline"
	RunnerRejected           = "rejected"
)

const (
	AssignmentAssigned  = "assigned"
	AssignmentDelivered = "delivered"
	AssignmentCancelled = "cancelled"
)

const (
	CancelReasonAdminBackupScan = "admin_backup_scan"
	CancelReasonAdminForce      = "admin_force_return"
	CancelReasonRejudge         = "rejudge"
	// Used by the dispatcher when CreateAssignment succeeded but the
	// follow-up SetRunnerStatus(busy) failed — we roll back the orphan row
	// instead of leaving a runner double-booked across dispatch passes.
	CancelReasonDispatchFailed = "dispatch_failed"
)

type Runner struct {
	ID             int64
	Name           string
	SessionToken   string
	Status         string
	CreatedAt      time.Time
	LastSeenAt     time.Time
	AvailableSince *time.Time
}

type Assignment struct {
	ID              int64
	BalloonID       int64
	RunnerID        int64
	State           string
	AssignedAt      time.Time
	DeliveredAt     *time.Time
	CancelledAt     *time.Time
	CancelledReason string
}

func newSessionToken() (string, error) {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf[:]), nil
}

// CreateRunner inserts a new runner row in pending_admit status and returns
// it. The session token is generated by the store.
func (s *Store) CreateRunner(name string) (Runner, error) {
	tok, err := newSessionToken()
	if err != nil {
		return Runner{}, fmt.Errorf("state: CreateRunner: token: %w", err)
	}
	now := time.Now().UTC()
	res, err := s.db.Exec(
		`INSERT INTO runners (name, session_token, status, created_at, last_seen_at)
		 VALUES (?, ?, ?, ?, ?)`,
		name, tok, RunnerPendingAdmit, now.Format(time.RFC3339Nano), now.Format(time.RFC3339Nano),
	)
	if err != nil {
		return Runner{}, fmt.Errorf("state: CreateRunner: %w", err)
	}
	id, _ := res.LastInsertId()
	return Runner{
		ID:           id,
		Name:         name,
		SessionToken: tok,
		Status:       RunnerPendingAdmit,
		CreatedAt:    now,
		LastSeenAt:   now,
	}, nil
}

func scanRunner(scanner interface {
	Scan(...any) error
}) (Runner, error) {
	var r Runner
	var createdAt, lastSeenAt string
	var availableSince sql.NullString
	if err := scanner.Scan(&r.ID, &r.Name, &r.SessionToken, &r.Status, &createdAt, &lastSeenAt, &availableSince); err != nil {
		return Runner{}, err
	}
	r.CreatedAt, _ = time.Parse(time.RFC3339Nano, createdAt)
	r.LastSeenAt, _ = time.Parse(time.RFC3339Nano, lastSeenAt)
	if availableSince.Valid {
		t, _ := time.Parse(time.RFC3339Nano, availableSince.String)
		r.AvailableSince = &t
	}
	return r, nil
}

const runnerCols = `id, name, session_token, status, created_at, last_seen_at, available_since`

// GetRunnerByToken returns the runner whose session_token matches. Used by the
// cookie auth middleware on every runner-facing RPC.
func (s *Store) GetRunnerByToken(tok string) (Runner, error) {
	row := s.db.QueryRow(`SELECT `+runnerCols+` FROM runners WHERE session_token = ?`, tok)
	r, err := scanRunner(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Runner{}, ErrNotFound
	}
	return r, err
}

func (s *Store) GetRunner(id int64) (Runner, error) {
	row := s.db.QueryRow(`SELECT `+runnerCols+` FROM runners WHERE id = ?`, id)
	r, err := scanRunner(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Runner{}, ErrNotFound
	}
	return r, err
}

// ListRunners returns every non-offline runner ordered by creation. Offline
// runners are excluded so the admin panel stays uncluttered after the contest;
// they remain in the table for audit.
func (s *Store) ListRunners() ([]Runner, error) {
	rows, err := s.db.Query(
		`SELECT ` + runnerCols + ` FROM runners WHERE status != '` + RunnerOffline + `' ORDER BY created_at ASC`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Runner
	for rows.Next() {
		r, err := scanRunner(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// ListAvailableRunners returns runners in `available` status ordered by
// available_since ascending (longest-waiting first). Used by the dispatcher.
func (s *Store) ListAvailableRunners() ([]Runner, error) {
	rows, err := s.db.Query(
		`SELECT `+runnerCols+` FROM runners WHERE status = ? ORDER BY available_since ASC, id ASC`,
		RunnerAvailable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Runner
	for rows.Next() {
		r, err := scanRunner(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// SetRunnerStatus transitions a runner to newStatus. If newStatus is
// `available`, available_since is set to now; otherwise it's cleared. The
// runner's last_seen_at is also bumped.
func (s *Store) SetRunnerStatus(id int64, newStatus string) (Runner, error) {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	var availableSince any
	if newStatus == RunnerAvailable {
		availableSince = now
	} else {
		availableSince = nil
	}
	_, err := s.db.Exec(
		`UPDATE runners SET status = ?, available_since = ?, last_seen_at = ? WHERE id = ?`,
		newStatus, availableSince, now, id,
	)
	if err != nil {
		return Runner{}, fmt.Errorf("state: SetRunnerStatus: %w", err)
	}
	return s.GetRunner(id)
}

// TouchRunner bumps last_seen_at to now. Called on every authenticated runner
// RPC so admins can see who's still active.
func (s *Store) TouchRunner(id int64) error {
	_, err := s.db.Exec(
		`UPDATE runners SET last_seen_at = ? WHERE id = ?`,
		time.Now().UTC().Format(time.RFC3339Nano), id,
	)
	return err
}

// --- Assignments ------------------------------------------------------------

// CreateAssignment inserts a new active assignment. Returns ErrConflict if the
// balloon already has an active assignment (the unique index catches it).
func (s *Store) CreateAssignment(balloonID, runnerID int64) (Assignment, error) {
	now := time.Now().UTC()
	res, err := s.db.Exec(
		`INSERT INTO assignments (balloon_id, runner_id, state, assigned_at)
		 VALUES (?, ?, ?, ?)`,
		balloonID, runnerID, AssignmentAssigned, now.Format(time.RFC3339Nano),
	)
	if err != nil {
		// modernc.org/sqlite returns errors with "UNIQUE constraint failed"
		// in the message; treat any insert failure as a conflict — the
		// caller's only sane recovery is to skip dispatch for this balloon.
		return Assignment{}, fmt.Errorf("state: CreateAssignment: %w", err)
	}
	id, _ := res.LastInsertId()
	return Assignment{
		ID:         id,
		BalloonID:  balloonID,
		RunnerID:   runnerID,
		State:      AssignmentAssigned,
		AssignedAt: now,
	}, nil
}

const assignmentCols = `id, balloon_id, runner_id, state, assigned_at, delivered_at, cancelled_at, cancelled_reason`

func scanAssignment(scanner interface {
	Scan(...any) error
}) (Assignment, error) {
	var a Assignment
	var assignedAt string
	var deliveredAt, cancelledAt, cancelledReason sql.NullString
	if err := scanner.Scan(&a.ID, &a.BalloonID, &a.RunnerID, &a.State, &assignedAt, &deliveredAt, &cancelledAt, &cancelledReason); err != nil {
		return Assignment{}, err
	}
	a.AssignedAt, _ = time.Parse(time.RFC3339Nano, assignedAt)
	if deliveredAt.Valid {
		t, _ := time.Parse(time.RFC3339Nano, deliveredAt.String)
		a.DeliveredAt = &t
	}
	if cancelledAt.Valid {
		t, _ := time.Parse(time.RFC3339Nano, cancelledAt.String)
		a.CancelledAt = &t
	}
	if cancelledReason.Valid {
		a.CancelledReason = cancelledReason.String
	}
	return a, nil
}

func (s *Store) GetAssignment(id int64) (Assignment, error) {
	row := s.db.QueryRow(`SELECT `+assignmentCols+` FROM assignments WHERE id = ?`, id)
	a, err := scanAssignment(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Assignment{}, ErrNotFound
	}
	return a, err
}

// ActiveAssignmentForRunner returns the runner's current `assigned`-state
// assignment, or ErrNotFound if none.
func (s *Store) ActiveAssignmentForRunner(runnerID int64) (Assignment, error) {
	row := s.db.QueryRow(
		`SELECT `+assignmentCols+` FROM assignments WHERE runner_id = ? AND state = ? LIMIT 1`,
		runnerID, AssignmentAssigned,
	)
	a, err := scanAssignment(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Assignment{}, ErrNotFound
	}
	return a, err
}

// ActiveAssignmentForBalloon returns the active assignment for the balloon, or
// ErrNotFound. Used by the dispatcher to skip already-assigned balloons and by
// the backup-scanner override to cancel them.
func (s *Store) ActiveAssignmentForBalloon(balloonID int64) (Assignment, error) {
	row := s.db.QueryRow(
		`SELECT `+assignmentCols+` FROM assignments WHERE balloon_id = ? AND state = ? LIMIT 1`,
		balloonID, AssignmentAssigned,
	)
	a, err := scanAssignment(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Assignment{}, ErrNotFound
	}
	return a, err
}

// ActiveAssignedRunnerNames returns a map balloon_id -> runner name for every
// assignment currently in `assigned` state. One query, no N+1.
func (s *Store) ActiveAssignedRunnerNames() (map[int64]string, error) {
	rows, err := s.db.Query(
		`SELECT a.balloon_id, r.name
		   FROM assignments a JOIN runners r ON r.id = a.runner_id
		  WHERE a.state = ?`,
		AssignmentAssigned,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := map[int64]string{}
	for rows.Next() {
		var bid int64
		var name string
		if err := rows.Scan(&bid, &name); err != nil {
			return nil, err
		}
		out[bid] = name
	}
	return out, rows.Err()
}

// ListActiveAssignments returns every assignment currently in `assigned`
// state. Used by the admin roster view to show "busy for Xm" badges.
func (s *Store) ListActiveAssignments() ([]Assignment, error) {
	rows, err := s.db.Query(
		`SELECT `+assignmentCols+` FROM assignments WHERE state = ? ORDER BY assigned_at ASC`,
		AssignmentAssigned,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Assignment
	for rows.Next() {
		a, err := scanAssignment(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}

// MarkAssignmentDelivered flips an assignment from `assigned` to `delivered`
// and stamps delivered_at. No-op if the assignment isn't `assigned`.
func (s *Store) MarkAssignmentDelivered(id int64) error {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	_, err := s.db.Exec(
		`UPDATE assignments SET state = ?, delivered_at = ? WHERE id = ? AND state = ?`,
		AssignmentDelivered, now, id, AssignmentAssigned,
	)
	return err
}

// CancelAssignment flips an `assigned` row to `cancelled` with a reason.
// No-op if the row is no longer assigned (e.g. already delivered).
func (s *Store) CancelAssignment(id int64, reason string) error {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	_, err := s.db.Exec(
		`UPDATE assignments SET state = ?, cancelled_at = ?, cancelled_reason = ? WHERE id = ? AND state = ?`,
		AssignmentCancelled, now, reason, id, AssignmentAssigned,
	)
	return err
}

var ErrNotFound = errors.New("state: not found")
